name: release 

on:
  push:
    branches:
      - master
    paths:
      - 'update.json'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read update.json
      id: setup
      run: |
        echo "VERSION=$(jq -r .version update.json)" >> $GITHUB_ENV
        echo "ZIP_NAME=$(basename $(jq -r .zipUrl update.json))" >> $GITHUB_ENV

    - name: Read changelog
      run: |
        CHANGELOG=$(git diff HEAD^ HEAD -- CHANGELOG.md | grep '^+[^+]' | sed 's/^+//; /---/d')
        echo "CHANGELOG<<CHANGELOG_EOF" >> $GITHUB_ENV
        echo "$CHANGELOG" >> $GITHUB_ENV
        echo "CHANGELOG_EOF" >> $GITHUB_ENV

    - name: Create dummy zip
      run: |
        cd module/dummy_zip
        cp -r ../META-INF .
        zip -r dummy.zip *
        mv dummy.zip ../

    - name: Create module zip
      run: |
        cd module
        zip -r "${{ env.ZIP_NAME }}" *

    - name: Validate release
      run: |
        git fetch --tags
        if git tag | grep -qx "^${{ env.VERSION }}"; then
          echo "RELEASE=false" >> $GITHUB_ENV
        else
          echo "RELEASE=true" >> $GITHUB_ENV
        fi

    - name: Create release
      if: env.RELEASE == 'true'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: "${{ env.VERSION }}"
        name: "${{ env.VERSION }}"
        body: "${{ env.CHANGELOG }}"
        draft: false
        files: "module/${{ env.ZIP_NAME }}" 
